import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, } from "@/components/ui/card";
import { useAuth } from "@/context/AuthContext";
const OnboardingWelcome = () => {
    const navigate = useNavigate();
    const { profile } = useAuth();
    const handleContinue = () => {
        navigate("/onboarding/company");
    };
    return (_jsxs("div", { className: "container max-w-5xl mx-auto px-4 py-12", children: [_jsxs("div", { className: "text-center mb-8", children: [_jsx("h1", { className: "text-3xl font-bold mb-4", children: "Welcome to Allora AI" }), _jsx("p", { className: "text-lg text-muted-foreground max-w-2xl mx-auto", children: "Your AI-powered executive advisory platform. Let's get you set up with a personalized experience." })] }), _jsxs(Card, { className: "mb-8", children: [_jsxs(CardHeader, { children: [_jsxs(CardTitle, { children: ["Welcome, ", (profile === null || profile === void 0 ? void 0 : profile.name) || "there", "!"] }), _jsx(CardDescription, { children: "Allora AI will help you make better business decisions with AI-powered insights." })] }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-4", children: [_jsx("p", { children: "Here's what you can expect from Allora AI:" }), _jsxs("div", { className: "grid md:grid-cols-2 gap-4", children: [_jsxs("div", { className: "p-4 border rounded-lg bg-primary/5", children: [_jsx("h3", { className: "font-medium mb-2", children: "AI Executive Team" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Access a virtual board of AI executives with specialized expertise in different business domains." })] }), _jsxs("div", { className: "p-4 border rounded-lg bg-primary/5", children: [_jsx("h3", { className: "font-medium mb-2", children: "Strategic Decision Making" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Get data-driven insights and recommendations tailored to your business context." })] }), _jsxs("div", { className: "p-4 border rounded-lg bg-primary/5", children: [_jsx("h3", { className: "font-medium mb-2", children: "Real-world Integration" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Connect with your business tools like Stripe, Calendly, and more for actionable intelligence." })] }), _jsxs("div", { className: "p-4 border rounded-lg bg-primary/5", children: [_jsx("h3", { className: "font-medium mb-2", children: "Personalized Strategy" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Receive strategies tailored to your industry, company size, and risk appetite." })] })] })] }) }), _jsx(CardFooter, { className: "flex justify-end", children: _jsx(Button, { onClick: handleContinue, children: "Continue to Setup" }) })] }), _jsx("div", { className: "text-center text-sm text-muted-foreground", children: _jsx("p", { children: "This will only take a few minutes to complete. Your information helps us personalize your experience." }) })] }));
};
export default OnboardingWelcome;
