import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import { PlusCircle } from "lucide-react";
const OnboardingIntegrations = () => {
    const navigate = useNavigate();
    const handleNext = () => {
        navigate("/onboarding/ai-workflow");
    };
    return (_jsxs("div", { className: "container max-w-5xl mx-auto px-4 py-12", children: [_jsxs("div", { className: "text-center mb-8", children: [_jsx("h1", { className: "text-3xl font-bold mb-4", children: "Connect Your Services" }), _jsx("p", { className: "text-lg text-muted-foreground max-w-2xl mx-auto", children: "Integrate your existing services with Allora AI to enhance your experience." })] }), _jsxs(Card, { className: "mb-8", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Integrations" }), _jsx(CardDescription, { children: "Connect your existing tools and services" })] }), _jsxs(CardContent, { className: "space-y-6", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsx(Card, { className: "border-dashed border-2 p-4 cursor-pointer hover:bg-muted/50 transition-colors", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(PlusCircle, { className: "h-8 w-8 text-muted-foreground" }), _jsxs("div", { children: [_jsx("h3", { className: "font-medium", children: "Connect CRM" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Salesforce, HubSpot, etc." })] })] }) }), _jsx(Card, { className: "border-dashed border-2 p-4 cursor-pointer hover:bg-muted/50 transition-colors", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(PlusCircle, { className: "h-8 w-8 text-muted-foreground" }), _jsxs("div", { children: [_jsx("h3", { className: "font-medium", children: "Connect Calendar" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Google Calendar, Outlook" })] })] }) }), _jsx(Card, { className: "border-dashed border-2 p-4 cursor-pointer hover:bg-muted/50 transition-colors", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(PlusCircle, { className: "h-8 w-8 text-muted-foreground" }), _jsxs("div", { children: [_jsx("h3", { className: "font-medium", children: "Connect Email" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Gmail, Outlook, etc." })] })] }) }), _jsx(Card, { className: "border-dashed border-2 p-4 cursor-pointer hover:bg-muted/50 transition-colors", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(PlusCircle, { className: "h-8 w-8 text-muted-foreground" }), _jsxs("div", { children: [_jsx("h3", { className: "font-medium", children: "Connect Analytics" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Google Analytics, etc." })] })] }) })] }), _jsx("p", { className: "text-sm text-muted-foreground", children: "You can skip this step and add integrations later." })] }), _jsxs(CardFooter, { className: "flex justify-between", children: [_jsx(Button, { variant: "outline", onClick: () => navigate("/onboarding/team"), children: "Back" }), _jsx(Button, { onClick: handleNext, children: "Continue" })] })] })] }));
};
export default OnboardingIntegrations;
