import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import { CheckCircle2 } from "lucide-react";
const OnboardingAIWorkflow = () => {
    const navigate = useNavigate();
    const handleNext = () => {
        navigate("/onboarding/complete");
    };
    return (_jsxs("div", { className: "container max-w-5xl mx-auto px-4 py-12", children: [_jsxs("div", { className: "text-center mb-8", children: [_jsx("h1", { className: "text-3xl font-bold mb-4", children: "Customize Your AI Workflow" }), _jsx("p", { className: "text-lg text-muted-foreground max-w-2xl mx-auto", children: "Select how you want to interact with your AI executive team." })] }), _jsxs(Card, { className: "mb-8", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "AI Executive Team Preferences" }), _jsx(CardDescription, { children: "Customize how your AI executives will collaborate and assist you" })] }), _jsx(CardContent, { className: "space-y-6", children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-start gap-3 p-3 border rounded-md", children: [_jsx(CheckCircle2, { className: "h-5 w-5 text-primary mt-0.5" }), _jsxs("div", { children: [_jsx("h3", { className: "font-medium", children: "Proactive Insights" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Allow your AI executives to proactively generate insights based on your company data" })] })] }), _jsxs("div", { className: "flex items-start gap-3 p-3 border rounded-md", children: [_jsx(CheckCircle2, { className: "h-5 w-5 text-primary mt-0.5" }), _jsxs("div", { children: [_jsx("h3", { className: "font-medium", children: "Executive Debates" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Enable your AI executives to debate strategic decisions with various perspectives" })] })] }), _jsxs("div", { className: "flex items-start gap-3 p-3 border rounded-md", children: [_jsx(CheckCircle2, { className: "h-5 w-5 text-primary mt-0.5" }), _jsxs("div", { children: [_jsx("h3", { className: "font-medium", children: "Risk Analysis" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Your AI team will analyze risk factors for every strategic suggestion" })] })] }), _jsxs("div", { className: "flex items-start gap-3 p-3 border rounded-md", children: [_jsx(CheckCircle2, { className: "h-5 w-5 text-primary mt-0.5" }), _jsxs("div", { children: [_jsx("h3", { className: "font-medium", children: "Implementation Planning" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Get detailed implementation plans for approved strategies" })] })] })] }) }), _jsxs(CardFooter, { className: "flex justify-between", children: [_jsx(Button, { variant: "outline", onClick: () => navigate("/onboarding/integrations"), children: "Back" }), _jsx(Button, { onClick: handleNext, children: "Finish Setup" })] })] })] }));
};
export default OnboardingAIWorkflow;
