import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import UserPreferencesDialog from "@/components/UserPreferencesDialog";
import { HelpButton } from "@/components/help/HelpButton";
import { BrainCog, Sparkles, Zap, Target, Settings } from "lucide-react";
import { motion } from "framer-motion";
import { Badge } from "@/components/ui/badge";
export function AiBotsHeader({ isMobileView }) {
    return (_jsxs("div", { className: "w-full space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between w-full", children: [_jsxs(motion.div, { initial: { opacity: 0, x: -20 }, animate: { opacity: 1, x: 0 }, transition: { duration: 0.5, ease: "easeOut" }, className: "flex flex-col gap-2", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "relative", children: [_jsx(motion.div, { className: "absolute inset-0 rounded-full bg-primary/20", animate: {
                                                    scale: [1, 1.2, 1],
                                                    opacity: [0.3, 0.5, 0.3],
                                                }, transition: {
                                                    duration: 3,
                                                    repeat: Infinity,
                                                    ease: "easeInOut",
                                                } }), _jsx(BrainCog, { className: "h-8 w-8 text-primary relative z-10" })] }), _jsx("h1", { className: "text-3xl font-bold tracking-tight", children: _jsx("span", { className: "bg-clip-text text-transparent bg-gradient-to-r from-primary via-primary-light to-primary", children: "AI Executive Team" }) }), _jsxs(Badge, { variant: "outline", className: "bg-black/30 text-primary border-primary/30 px-2 py-1 backdrop-blur-md", children: [_jsx(Sparkles, { className: "h-3 w-3 mr-1" }), " Advanced"] })] }), _jsx("p", { className: "text-muted-foreground ml-11", children: "Your elite team of AI executives for strategic business guidance and insights" })] }), _jsx(HelpButton, { contextId: "ai-bots", variant: "premium" })] }), _jsxs(motion.div, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.2, duration: 0.5 }, className: "flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 w-full relative", children: [_jsxs("div", { className: "relative z-10", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 bg-gradient-to-r from-blue-600/20 to-blue-400/5 rounded-xl", children: _jsx(BrainCog, { className: "h-6 w-6 text-blue-400" }) }), _jsxs("div", { children: [_jsx("h2", { className: `${isMobileView ? "text-xl" : "text-2xl"} font-bold tracking-tight`, children: "Executive Boardroom" }), _jsx("p", { className: "text-sm text-muted-foreground mt-1", children: "Advanced AI-driven strategic analysis and business insights" })] })] }), _jsxs("div", { className: "flex gap-2 mt-4 flex-wrap", children: [_jsxs(Badge, { variant: "outline", className: "bg-blue-500/10 border-blue-500/30 text-blue-400 flex items-center gap-1", children: [_jsx(Target, { className: "h-3 w-3" }), " Strategic Planning"] }), _jsxs(Badge, { variant: "outline", className: "bg-purple-500/10 border-purple-500/30 text-purple-400 flex items-center gap-1", children: [_jsx(Zap, { className: "h-3 w-3" }), " Operational Excellence"] }), _jsxs(Badge, { variant: "outline", className: "bg-amber-500/10 border-amber-500/30 text-amber-400 flex items-center gap-1", children: [_jsx(Sparkles, { className: "h-3 w-3" }), " Innovation"] })] })] }), _jsx(motion.div, { whileHover: { scale: 1.03 }, whileTap: { scale: 0.97 }, children: _jsx(UserPreferencesDialog, { triggerLabel: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Settings, { className: "h-4 w-4" }), isMobileView ? "AI Settings" : "AI Response Settings"] }) }) })] })] }));
}
