import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow, } from "@/components/ui/table";
import { useBreakpoint } from "@/hooks/use-mobile";
export const UserListSkeleton = () => {
    const breakpoint = useBreakpoint();
    const isMobileView = ["xs", "mobile"].includes(breakpoint);
    if (isMobileView) {
        return (_jsx("div", { className: "space-y-4", children: Array.from({ length: 5 }).map((_, index) => (_jsxs("div", { className: "border border-white/10 rounded-md p-4 bg-[#111827] shadow-sm", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(Skeleton, { className: "h-10 w-10 rounded-full bg-[#1E293B] mr-3" }), _jsxs("div", { children: [_jsx(Skeleton, { className: "h-4 w-32 bg-[#1E293B] mb-2" }), _jsx(Skeleton, { className: "h-3 w-40 bg-[#1E293B]" })] })] }), _jsx(Skeleton, { className: "h-6 w-16 bg-[#1E293B] rounded-full" })] }), _jsxs("div", { className: "flex gap-2 mt-3", children: [_jsx(Skeleton, { className: "h-8 flex-1 bg-[#1E293B]" }), _jsx(Skeleton, { className: "h-8 flex-1 bg-[#1E293B]" })] })] }, index))) }));
    }
    return (_jsx("div", { className: "rounded-md border border-white/10 overflow-x-auto bg-[#111827]", children: _jsxs(Table, { children: [_jsx(TableHeader, { className: "bg-[#1A1F2C]", children: _jsxs(TableRow, { className: "border-white/10 hover:bg-transparent", children: [_jsx(TableHead, { className: "text-gray-400", children: "Name" }), _jsx(TableHead, { className: "text-gray-400", children: "Email" }), _jsx(TableHead, { className: "text-gray-400", children: "Role" }), _jsx(TableHead, { className: "hidden md:table-cell text-gray-400", children: "Created" }), _jsx(TableHead, { className: "text-gray-400", children: "Actions" })] }) }), _jsx(TableBody, { children: Array.from({ length: 5 }).map((_, index) => (_jsxs(TableRow, { className: "border-white/10", children: [_jsx(TableCell, { children: _jsx(Skeleton, { className: "h-5 w-32 bg-[#1E293B]" }) }), _jsx(TableCell, { children: _jsx(Skeleton, { className: "h-5 w-40 bg-[#1E293B]" }) }), _jsx(TableCell, { children: _jsx(Skeleton, { className: "h-6 w-16 bg-[#1E293B] rounded-full" }) }), _jsx(TableCell, { className: "hidden md:table-cell", children: _jsx(Skeleton, { className: "h-5 w-24 bg-[#1E293B]" }) }), _jsx(TableCell, { children: _jsxs("div", { className: "flex gap-2", children: [_jsx(Skeleton, { className: "h-8 w-24 bg-[#1E293B]" }), _jsx(Skeleton, { className: "h-8 w-20 bg-[#1E293B]" })] }) })] }, index))) })] }) }));
};
