export * from "./admin-routes";
export * from "./auth-routes";
export * from "./dashboard-routes";
export * from "./onboarding-routes";
export * from "./marketing-routes";
export * from "./dev-routes";
export * from "./global-routes";
export * from "./galaxy-routes";
export * from "./academy-routes";
export * from "./vault-routes";
export { AppRoutes } from "./AppRoutes";
