
import { CallScript } from "./types";
import { generateScriptContent, generateMessageContent, getExecutiveScripts } from "./scriptGenerators";
import { InsightType } from "@/components/bot-insights/BotInsightCard";

/**
 * Creates AI-generated scripts from company insights
 */
export const createAiGeneratedScripts = (
  insights: any[], 
  companyName?: string, 
  industry?: string
): CallScript[] => {
  // Filter for call script insights
  const callScriptInsights = insights.filter(insight => insight.type === "call_script" as InsightType);
  
  // Generate call scripts from insights
  const aiGeneratedCallScripts = callScriptInsights.map(insight => ({
    id: insight.id,
    title: insight.title,
    target: `${insight.primaryBot.name}'s Recommendations`,
    duration: "4-5 min",
    status: "Ready" as const,
    content: insight.description || generateScriptContent(
      insight.title, 
      insight.primaryBot.name, 
      insight.primaryBot.role, 
      companyName
    ),
    aiGenerated: true,
    primaryBot: insight.primaryBot,
    collaborators: insight.collaborators,
    type: 'call' as const
  }));
  
  // Generate complementary message scripts
  const aiGeneratedMessageScripts: CallScript[] = aiGeneratedCallScripts.map(script => ({
    id: `${script.id}-message`,
    title: `Follow-up for: ${script.title}`,
    target: script.target,
    duration: "1-2 min",
    status: "Ready",
    content: generateMessageContent(script.title, script.target, industry || "Technology"),
    aiGenerated: true,
    primaryBot: script.primaryBot,
    collaborators: script.collaborators,
    type: 'message' as const
  }));
  
  return [...aiGeneratedCallScripts, ...aiGeneratedMessageScripts];
};

/**
 * Creates scripts generated by the executive collective based on company profile
 */
export const createExecutiveCollectiveScripts = (
  companyName?: string,
  industry?: string,
  companySize?: string
): CallScript[] => {
  // Define executive roles based on company size and industry
  const executiveRoles = [
    { role: "Sales Development Director", specialty: "sales" },
    { role: "Chief Marketing Strategist", specialty: "marketing" },
    { role: "Growth Optimization Consultant", specialty: "strategy" },
    { role: "VP of Business Development", specialty: "sales" },
    { role: "Customer Acquisition Specialist", specialty: "marketing" }
  ];
  
  // Generate scripts from all executive roles
  return executiveRoles.flatMap(exec => 
    getExecutiveScripts(exec.role, industry || "Technology", companyName)
  );
};
