import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CheckCircle2, XCircle, AlertTriangle, Code } from "lucide-react";
export function DatabaseFunctionsCheck({ functions }) {
    if (!functions || functions.length === 0)
        return null;
    // Count function issues
    const functionIssues = functions.filter((f) => !f.exists || !f.isSecure).length;
    return (_jsxs("div", { className: "rounded-md border border-border/60 overflow-hidden", children: [_jsxs("div", { className: "bg-muted/30 px-4 py-3 font-medium border-b border-border/60 flex justify-between items-center", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Code, { className: "h-4 w-4 text-purple-500" }), _jsx("span", { children: "Database Functions" })] }), functionIssues > 0 ? (_jsxs("span", { className: "text-xs px-2 py-1 bg-red-100 text-red-800 rounded-full", children: [functionIssues, " issues"] })) : (_jsx("span", { className: "text-xs px-2 py-1 bg-green-100 text-green-800 rounded-full", children: "All configured" }))] }), _jsx("div", { className: "divide-y divide-border/60", children: functions.map((func) => (_jsxs("div", { className: "px-4 py-3", children: [_jsxs("div", { className: "flex items-center justify-between mb-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [func.exists ? (_jsx(CheckCircle2, { className: "h-5 w-5 text-green-500" })) : (_jsx(XCircle, { className: "h-5 w-5 text-red-500" })), _jsx("span", { className: "font-medium", children: func.name })] }), _jsx("span", { className: `text-sm ${func.exists ? "text-green-600" : "text-red-600"}`, children: func.exists ? "Exists" : "Missing" })] }), func.exists && (_jsx("div", { className: "flex items-center pl-7 mt-1", children: _jsxs("div", { className: "flex items-center gap-2", children: [func.isSecure ? (_jsx(CheckCircle2, { className: "h-4 w-4 text-green-500" })) : (_jsx(AlertTriangle, { className: "h-4 w-4 text-amber-500" })), _jsx("span", { className: "text-sm text-muted-foreground", children: func.isSecure
                                            ? "SECURITY DEFINER"
                                            : "Not using SECURITY DEFINER" })] }) }))] }, func.name))) })] }));
}
