import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Helmet } from "react-helmet-async";
import { AIPreferencesForm } from "@/components/ai/AiPreferencesForm";
import { AiBehaviorSettings } from "@/components/ai/AiBehaviorSettings";
import { ModelPreferences } from "@/components/ai-settings/ModelPreferences";
import { LearningSettings } from "@/components/ai-settings/LearningSettings";
import { Settings, BookOpen } from "lucide-react";
import { PageTitle } from "@/components/PageTitle";
export default function AISettings() {
    return (_jsxs("div", { className: "container mx-auto py-6 space-y-6", children: [_jsx(Helmet, { children: _jsx("title", { children: "AI Settings | Allora AI" }) }), _jsx(PageTitle, { title: "AI Settings & Preferences", description: "Customize how the AI executive team behaves and makes decisions", children: _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Settings, { className: "h-5 w-5 text-primary" }), _jsx("span", { children: "AI Control Center" })] }) }), _jsxs(Card, { className: "w-full", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "AI Executive Settings" }), _jsx(CardDescription, { children: "Configure how your AI executives analyze and generate business strategies" })] }), _jsx(CardContent, { children: _jsxs(Tabs, { defaultValue: "behavior", className: "w-full", children: [_jsxs(TabsList, { className: "grid w-full grid-cols-2 md:grid-cols-4", children: [_jsx(TabsTrigger, { value: "behavior", children: "Behavior" }), _jsx(TabsTrigger, { value: "preferences", children: "Preferences" }), _jsx(TabsTrigger, { value: "models", children: "AI Models" }), _jsx(TabsTrigger, { value: "learning", children: "Learning" })] }), _jsx(TabsContent, { value: "behavior", className: "py-4", children: _jsx(AiBehaviorSettings, {}) }), _jsx(TabsContent, { value: "preferences", className: "py-4", children: _jsx(AIPreferencesForm, {}) }), _jsx(TabsContent, { value: "models", className: "py-4", children: _jsx(ModelPreferences, {}) }), _jsx(TabsContent, { value: "learning", className: "py-4", children: _jsx(LearningSettings, {}) })] }) })] }), _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(BookOpen, { className: "h-5 w-5" }), "AI Learning Documentation"] }), _jsx(CardDescription, { children: "Learn more about how the AI executives learn and adapt to your business needs" })] }), _jsx(CardContent, { children: _jsxs("div", { className: "prose", children: [_jsx("p", { children: "Our AI executives continually learn from your feedback and interactions. The more you engage with them, the better they'll understand your business needs and goals." }), _jsx("h4", { children: "Key learning mechanisms:" }), _jsxs("ul", { children: [_jsx("li", { children: "Direct feedback on recommendations" }), _jsx("li", { children: "Strategy implementation tracking" }), _jsx("li", { children: "Business outcome correlation" }), _jsx("li", { children: "Industry pattern recognition" })] })] }) })] })] }));
}
