import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Filter, Search, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue, } from "@/components/ui/select";
import { format, addMonths, subMonths } from "date-fns";
export function SocialMediaFilters({ currentMonth, onMonthChange, searchQuery, onSearchChange, selectedPlatform, onPlatformChange, selectedStatus, onStatusChange, onApplyFilters, onClearFilters, }) {
    return (_jsx(Card, { children: _jsx(CardContent, { className: "p-4", children: _jsxs("form", { onSubmit: onApplyFilters, className: "grid grid-cols-1 md:grid-cols-5 gap-4", children: [_jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" }), _jsx(Input, { placeholder: "Search posts...", className: "pl-8", value: searchQuery, onChange: (e) => onSearchChange(e.target.value) })] }), _jsxs(Select, { value: selectedPlatform, onValueChange: onPlatformChange, children: [_jsx(SelectTrigger, { children: _jsx(SelectValue, { placeholder: "Platform" }) }), _jsxs(SelectContent, { children: [_jsx(SelectItem, { value: "", children: "All Platforms" }), _jsx(SelectItem, { value: "Facebook", children: "Facebook" }), _jsx(SelectItem, { value: "Instagram", children: "Instagram" }), _jsx(SelectItem, { value: "LinkedIn", children: "LinkedIn" }), _jsx(SelectItem, { value: "Twitter", children: "Twitter" }), _jsx(SelectItem, { value: "TikTok", children: "TikTok" })] })] }), _jsxs(Select, { value: selectedStatus, onValueChange: onStatusChange, children: [_jsx(SelectTrigger, { children: _jsx(SelectValue, { placeholder: "Status" }) }), _jsxs(SelectContent, { children: [_jsx(SelectItem, { value: "", children: "All Statuses" }), _jsx(SelectItem, { value: "draft", children: "Draft" }), _jsx(SelectItem, { value: "scheduled", children: "Scheduled" }), _jsx(SelectItem, { value: "published", children: "Published" }), _jsx(SelectItem, { value: "failed", children: "Failed" })] })] }), _jsx("div", { children: _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Button, { variant: "outline", type: "button", onClick: () => onMonthChange(subMonths(currentMonth, 1)), size: "icon", children: _jsx(ChevronLeft, { className: "h-4 w-4" }) }), _jsx("span", { className: "font-medium", children: format(currentMonth, "MMMM yyyy") }), _jsx(Button, { variant: "outline", type: "button", onClick: () => onMonthChange(addMonths(currentMonth, 1)), size: "icon", children: _jsx(ChevronRight, { className: "h-4 w-4" }) })] }) }), _jsxs("div", { className: "flex space-x-2", children: [_jsxs(Button, { type: "submit", variant: "default", className: "w-full", children: [_jsx(Filter, { className: "mr-2 h-4 w-4" }), "Apply Filters"] }), _jsx(Button, { type: "button", variant: "outline", onClick: onClearFilters, children: "Clear" })] })] }) }) }));
}
