// AI Executive Team - These are the AI personas that function as virtual executives
export const executiveBots = {
  // C-Suite
  ceo: ["Elon Musk", "Jeff Bezos", "Satya Nadella", "Tim Cook"],
  coo: [
    "Sheryl Sandberg",
    "Gwynne Shotwell",
    "Jeffrey Bezos (COO Mode)",
    "Anne Mulcahy",
  ],
  cfo: [
    "Warren Buffett",
    "Ruth Porat",
    "David Wehner",
    "Kelly R. Bennett",
    "Michael S. Dell",
    "Jamie Dimon",
  ],
  cio: [
    "Satya Nadella",
    "Bob Lord",
    "Cynthia Stoddard",
    "Abby Kohnstamm",
    "Caterina Fake",
  ],
  cto: [
    "Mike Schroepfer",
    "Werner Vogels",
    "Parag Agrawal",
    "Anders Hejlsberg",
  ],
  cmo: [
    "Antonio Lucio",
    "Phil Schiller",
    "Keith Weed",
    "Mindy Grossman",
    "Seth Godin",
  ],
  chro: ["Pat Wadors", "Jenny Dearborn", "Laszlo Bock", "Anu Monga"],

  // VPs and Directors
  vp_sales: [
    "Mike Weinberg",
    "Grant Cardone",
    "Brian Tracy",
    "Zig Ziglar",
    "Jill Konrath",
  ],
  vp_product: ["Marissa Mayer", "Sundar Pichai", "Julie Zhuo", "Des Traynor"],
  vp_operations: [
    "Gwynne Shotwell",
    "Tim Cook",
    "Jeff Wilke",
    "Rosalind Brewer",
  ],
  vp_marketing: [
    "Phil Schiller",
    "Antonio Lucio",
    "Beth Comstock",
    "Bozoma Saint John",
  ],
  digital_marketing: [
    "Neil Patel",
    "Gary Vaynerchuk",
    "Rand Fishkin",
    "Avinash Kaushik",
  ],
  seo_specialist: ["Rand Fishkin", "Moz Team", "Ahrefs Team", "Marie Haynes"],
  ppc_specialist: [
    "Brad Geddes",
    "Larry Kim",
    "Samantha Noble",
    "Frederick Vallaeys",
  ],

  // Technical Specialists
  data_scientist: [
    "Yann LeCun",
    "Andrew Ng",
    "Geoffrey Hinton",
    "Fei-Fei Li",
    "DJ Patil",
  ],
  ml_engineer: [
    "Demis Hassabis",
    "Ian Goodfellow",
    "Andrej Karpathy",
    "Christopher Manning",
  ],
  software_engineer: [
    "Kent Beck",
    "Martin Fowler",
    "Linus Torvalds",
    "Guido van Rossum",
  ],
  cloud_architect: [
    "Urs Hölzle",
    "Werner Vogels",
    "James Gosling",
    "Adrian Cockcroft",
  ],
  blockchain_developer: [
    "Vitalik Buterin",
    "Gavin Wood",
    "Charles Hoskinson",
    "Joseph Lubin",
  ],

  // Business and Strategy
  strategy: [
    "Clayton Christensen",
    "Brian Chesky",
    "Reed Hastings",
    "Marissa Mayer",
  ],
  business_analyst: [
    "Thomas Davenport",
    "Michael Porter",
    "Jim Collins",
    "Peter Drucker",
  ],
  growth_hacker: ["Andrew Chen", "Sean Ellis", "Noah Kagan", "Hiten Shah"],
  innovation_manager: [
    "Clayton Christensen",
    "W. Chan Kim",
    "Steve Blank",
    "Eric Ries",
  ],
  brand_strategist: [
    "Keith Weed",
    "Cindy Gallop",
    "Martin Lindstrom",
    "Wally Olins",
  ],

  // Finance and Investment
  venture_capitalist: [
    "Peter Thiel",
    "Marc Andreessen",
    "Mary Meeker",
    "Bill Gurley",
  ],
  investment_banker: [
    "Jamie Dimon",
    "Lloyd Blankfein",
    "Adena Friedman",
    "James Gorman",
  ],
  risk_manager: ["Warren Buffett", "Ray Dalio", "Robert Rubin", "Sheila Bair"],
  financial_advisor: [
    "Suze Orman",
    "Dave Ramsey",
    "Ramit Sethi",
    "Robert Kiyosaki",
  ],

  // Operations and Logistics
  supply_chain_manager: [
    "Doug McMillon",
    "Tim Cook",
    "Mary Barra",
    "Frederick W. Smith",
  ],
  manufacturing_engineer: [
    "Elon Musk",
    "Jeff Bezos",
    "Shigefumi Goto",
    "Taiichi Ohno",
  ],
  transportation_manager: [
    "Elon Musk",
    "Richard Branson",
    "Ed Bastian",
    "Frederick W. Smith",
  ],
  aviation_manager: [
    "Akbar Al Baker",
    "Richard Branson",
    "Alan Joyce",
    "Carsten Spohr",
  ],

  // Legal and Compliance
  legal_counsel: [
    "David Boies",
    "Ruth Bader Ginsburg",
    "Mary Jo White",
    "Wachtell Lipton Team",
  ],
  compliance_officer: [
    "Mary Jo White",
    "Jay Clayton",
    "Kenneth Feinberg",
    "Preet Bharara",
  ],

  // UX/UI and Design
  ux_designer: ["Jonathan Ive", "Don Norman", "Steve Krug", "Jakob Nielsen"],
  architect: ["Norman Foster", "Zaha Hadid", "Rem Koolhaas", "Frank Gehry"],
  civil_engineer: [
    "Isambard Brunel",
    "Gustave Eiffel",
    "Leslie Robertson",
    "Fazlur Rahman Khan",
  ],
  structural_engineer: [
    "Santiago Calatrava",
    "Ove Arup",
    "Peter Rice",
    "Leslie Robertson",
  ],
  fashion_designer: [
    "Coco Chanel",
    "Giorgio Armani",
    "Donatella Versace",
    "Tom Ford",
  ],

  // Special Sectors
  sustainability_officer: [
    "Christiana Figueres",
    "Al Gore",
    "Gro Harlem Brundtland",
    "Paul Polman",
  ],
  biotech_scientist: [
    "Jennifer Doudna",
    "George Church",
    "Craig Venter",
    "Feng Zhang",
  ],
  genetic_engineer: [
    "Feng Zhang",
    "Jennifer Doudna",
    "George Church",
    "Emmanuelle Charpentier",
  ],
  medical_doctor: [
    "Valentin Fuster",
    "Atul Gawande",
    "Anthony Fauci",
    "Eric Topol",
  ],
  neurosurgeon: ["Sanjay Gupta", "Ben Carson", "Henry Marsh", "James Watson"],

  // AI Ethics and Security
  ai_ethics_researcher: [
    "Timnit Gebru",
    "Kate Crawford",
    "Joy Buolamwini",
    "Meredith Whittaker",
  ],
  cybersecurity_specialist: [
    "Kevin Mitnick",
    "Bruce Schneier",
    "Mikko Hypponen",
    "Brian Krebs",
  ],

  // Media and Communications
  content_creator: [
    "MrBeast",
    "Casey Neistat",
    "Peter McKinnon",
    "Lilly Singh",
  ],
  public_relations: [
    "Richard Edelman",
    "Harold Burson",
    "Dan Edelman",
    "Melissa Waggener",
  ],
  journalist: [
    "Christiane Amanpour",
    "Anderson Cooper",
    "Kara Swisher",
    "Walt Mossberg",
  ],
  diplomat: [
    "Kofi Annan",
    "Madeleine Albright",
    "Henry Kissinger",
    "Ban Ki-moon",
  ],

  // Entertainment and Hospitality
  music_producer: ["Rick Rubin", "Dr. Dre", "Quincy Jones", "Max Martin"],
  film_director: [
    "Steven Spielberg",
    "Christopher Nolan",
    "Kathryn Bigelow",
    "Quentin Tarantino",
  ],
  actor: ["Meryl Streep", "Tom Hanks", "Daniel Day-Lewis", "Viola Davis"],
  food_beverage_director: [
    "José Andrés",
    "Gordon Ramsay",
    "Alice Waters",
    "Thomas Keller",
  ],
  hospitality_manager: [
    "Arne Sorenson",
    "Bill Marriott",
    "Ian Schrager",
    "Isadore Sharp",
  ],

  // Customer Success and Service
  customer_success: [
    "Nick Mehta",
    "Tony Hsieh",
    "Lincoln Murphy",
    "Jeffrey Pfeffer",
    "Ann-Marie Campbell",
  ],
  call_center_manager: [
    "Tony Hsieh",
    "Jeff Bezos",
    "Richard Branson",
    "Herb Kelleher",
  ],

  // Sales and Business Development
  sales_business_development: ["Marc Benioff", "Howard Schultz", "Mary Barra"],
  cold_calling: ["Grant Cardone", "Brian Tracy", "Zig Ziglar", "Jill Konrath"],
  lead_qualification: ["Trish Bertuzzi", "Mike Weinberg"],

  // E-commerce and Retail
  retail_manager: [
    "Doug McMillon",
    "Mickey Drexler",
    "Angela Ahrendts",
    "Stacey Widlitz",
  ],
  ecommerce_director: ["Jeff Bezos", "Jack Ma", "Michael Dubin", "Marc Lore"],
  luxury_brand_manager: [
    "Bernard Arnault",
    "François-Henri Pinault",
    "Miuccia Prada",
    "Patrizio Bertelli",
  ],

  // Sports and Education
  sports_coach: [
    "Pep Guardiola",
    "Phil Jackson",
    "Alex Ferguson",
    "Bill Belichick",
  ],
  sports_agent: ["Scott Boras", "Jeff Schwartz", "Rich Paul", "Mino Raiola"],
  education_consultant: [
    "Sal Khan",
    "Ken Robinson",
    "Sugata Mitra",
    "Carol Dweck",
  ],
  university_president: [
    "Drew Faust",
    "Rafael Reif",
    "John Hennessy",
    "Lawrence Bacow",
  ],

  // Real Estate and Construction
  real_estate_broker: [
    "Ryan Serhant",
    "Barbara Corcoran",
    "Grant Cardone",
    "Josh Altman",
  ],
  construction_manager: [
    "Jorge Pérez",
    "Steve Wynn",
    "Donald Trump",
    "Sam Zell",
  ],

  // Gaming and Immersive Tech
  vr_ar_developer: [
    "Palmer Luckey",
    "John Carmack",
    "Brendan Iribe",
    "Michael Abrash",
  ],
  game_designer: [
    "Shigeru Miyamoto",
    "Hideo Kojima",
    "Will Wright",
    "Sid Meier",
  ],
  esports_coach: ["Danny Sørensen", "Kim Jeong-soo", "Cain", "Kkoma"],

  // Event Planning
  event_planner: [
    "Mindy Weiss",
    "Preston Bailey",
    "David Tutera",
    "Colin Cowie",
  ],

  // Special Operations
  operations_efficiency: [
    "Indra Nooyi",
    "Tim Cook",
    "Mary Barra",
    "Greg Brenneman",
  ],
  political_campaign_manager: [
    "David Axelrod",
    "Kellyanne Conway",
    "James Carville",
    "Karl Rove",
  ],
  strategic_partnerships: [
    "Sheryl Sandberg",
    "Satya Nadella",
    "Tim Cook",
    "Marc Benioff",
  ],
  renewable_energy_engineer: ["Elon Musk", "Bill Gross", "Akon", "Lynn Jurich"],
  electric_vehicle_engineer: [
    "JB Straubel",
    "Elon Musk",
    "Henrik Fisker",
    "Peter Rawlinson",
  ],
  aerospace_engineer: [
    "Gwynne Shotwell",
    "Elon Musk",
    "Burt Rutan",
    "Kelly Johnson",
  ],

  // Marketing
  marketing: ["Seth Godin", "Gary Vaynerchuk", "Rand Fishkin", "Neil Patel"],
};

// Additional specialized industry-specific executives
export const industrySpecificExecutives = {
  healthcare: {
    cmo: ["Angela Hwang", "Emma Walmsley", "Vas Narasimhan"],
    chro: ["Bernard J. Tyson", "Carla Irwin", "David Feinberg"],
    compliance: [
      "Catherine Corley",
      "Richard Sauber",
      "Melissa Stapleton Barnes",
    ],
    strategic_partnerships: ["Jessica Mega", "Kieran Murphy", "Joaquin Duato"],
  },
  technology: {
    cio: ["Satya Nadella", "Sarah Friar", "Safra Catz"],
    cto: ["Werner Vogels", "Mike Schroepfer", "Parag Agrawal"],
    security: ["Christopher Krebs", "Katie Moussouris", "Bruce Schneier"],
    product_strategy: ["Marissa Mayer", "Sundar Pichai", "Lisa Su"],
  },
  finance: {
    cfo: ["Ruth Porat", "Jamie Dimon", "Jane Fraser"],
    risk_officer: ["Sarah Dahlgren", "Brian Moynihan", "Marianne Lake"],
    investment_advisor: ["Ray Dalio", "Cathie Wood", "Howard Marks"],
    regulatory_compliance: ["Mary Schapiro", "Gary Gensler", "Hester Peirce"],
  },
  retail: {
    cmo: ["Seth Godin", "Bozoma Saint John", "Marc Pritchard"],
    supply_chain: ["Tim Cook", "Alexis Maybank", "Dave Clark"],
    customer_experience: ["Tony Hsieh", "Horst Schulze", "Shep Hyken"],
    ecommerce_director: ["Daniel Zhang", "Julie Wainwright", "Kunal Bahl"],
  },
  manufacturing: {
    operations: ["Tim Cook", "Mary Barra", "Gwynne Shotwell"],
    supply_chain: ["Liz Elting", "Annette Clayton", "Ruth Hartman"],
    quality_control: ["W. Edwards Deming", "Joseph Juran", "Mary Walton"],
    innovation_manager: ["Jim Hackett", "Marillyn Hewson", "Alan Mulally"],
  },
};

// Defines the output locations for each role
export const botOutputLocations = {
  ceo: "Dashboard Strategy",
  coo: "Admin Panel / Reports",
  cfo: "Finance Dashboard",
  cio: "IT Panel",
  cto: "Product Roadmap",
  cmo: "Campaign Manager",
  chro: "HR Dashboard",
  vp_sales: "Calls / Messaging",
  vp_product: "Product Dashboard",
  vp_operations: "Operations Panel",
  data_scientist: "Analytics Dashboard",
  ml_engineer: "AI R&D Lab",
  chief_data_officer: "Data Panel",
  ux_designer: "UX Reports",
  brand_strategist: "Brand Manager",
  innovation_manager: "Innovation Lab",
  supply_chain_manager: "Supply Chain Panel",
  manufacturing_engineer: "Manufacturing Report",
  venture_capitalist: "Investment Manager",
  investment_banker: "Finance Panel",
  risk_manager: "Strategy Risk Section",
  marketing: "Campaigns Dashboard",
  growth_hacker: "Growth Lab",
  software_engineer: "Developer Dashboard",
  cloud_architect: "IT Operations Panel",
  blockchain_developer: "Blockchain Lab",
  ai_ethics_researcher: "Ethics Center",
  legal_counsel: "Legal Section",
  cybersecurity_specialist: "Security Center",
  content_creator: "Content Studio",
  public_relations: "PR Panel",
  journalist: "Media Center",
  diplomat: "Diplomatic Relations",
  political_campaign_manager: "Advocacy Board",
  strategic_partnerships: "Partner Manager",
  sustainability_officer: "Sustainability Tracker",
  renewable_energy_engineer: "Sustainability Center",
  electric_vehicle_engineer: "EV Lab",
  aerospace_engineer: "Space Tech Board",
  architect: "Architecture Panel",
  civil_engineer: "Engineering Board",
  structural_engineer: "Structures Board",
  fashion_designer: "Fashion Center",
  luxury_brand_manager: "Brand HQ",
  retail_manager: "Retail Dashboard",
  ecommerce_director: "E-commerce Dashboard",
  food_beverage_director: "Hospitality Manager",
  hospitality_manager: "Hospitality HQ",
  sports_coach: "Sports Lab",
  sports_agent: "Sports Agency Panel",
  education_consultant: "Education Center",
  university_president: "University HQ",
  financial_advisor: "Finance Advice Portal",
  real_estate_broker: "Real Estate Hub",
  construction_manager: "Construction Center",
  music_producer: "Music Lab",
  film_director: "Film Studio",
  actor: "Talent Studio",
  digital_marketing: "Digital Marketing Hub",
  seo_specialist: "SEO Dashboard",
  ppc_specialist: "PPC Manager",
  vr_ar_developer: "VR Lab",
  game_designer: "Game Studio",
  esports_coach: "Esports Training Hub",
  customer_success: "Customer Success Center",
  call_center_manager: "Call Center Manager",
  event_planner: "Events Manager",
  transportation_manager: "Transport Hub",
  aviation_manager: "Aviation Manager",
  biotech_scientist: "Biotech Lab",
  genetic_engineer: "Biotech Lab",
  medical_doctor: "Health Panel",
  neurosurgeon: "Healthcare AI",
  business_analyst: "Business Reports",
  compliance_officer: "Compliance Center",
  cold_calling: "Calls / Messaging",
  lead_qualification: "Calls / Messaging",
  sales_business_development: "Partner Manager",
};

// Define special skills for each role
export const botSpecialSkills = {
  ceo: "Risk-taking, market disruption",
  coo: "Team scaling, efficiency",
  cfo: "Cash flow optimization",
  cio: "Digital transformation",
  cto: "Tech innovation",
  cmo: "Brand expansion",
  chro: "Team building, retention",
  vp_sales: "Sales funnels, cold outreach",
  vp_product: "UX and feature prioritization",
  vp_operations: "Supply chain mastery",
  data_scientist: "Predictive analytics",
  ml_engineer: "Neural networks",
  chief_data_officer: "Data quality enforcement",
  ux_designer: "Intuitive design",
  brand_strategist: "CSR integration",
  innovation_manager: "Innovator's dilemma application",
  supply_chain_manager: "Warehousing",
  manufacturing_engineer: "Factory efficiency",
  venture_capitalist: "Risk analysis",
  investment_banker: "IPO guidance",
  risk_manager: "Conservative growth",
  marketing: "Launch events",
  growth_hacker: "User acquisition",
  software_engineer: "Agile development",
  cloud_architect: "Scalability",
  blockchain_developer: "Crypto innovation",
  ai_ethics_researcher: "Bias mitigation",
  legal_counsel: "Litigation support",
  cybersecurity_specialist: "Penetration testing",
  content_creator: "YouTube growth",
  public_relations: "Media relations",
  journalist: "Storytelling",
  diplomat: "Cross-cultural leadership",
  political_campaign_manager: "Voter engagement",
  strategic_partnerships: "Enterprise sales",
  sustainability_officer: "Emissions reduction",
  renewable_energy_engineer: "Solar energy",
  electric_vehicle_engineer: "Battery design",
  aerospace_engineer: "Rocket logistics",
  architect: "Smart cities",
  civil_engineer: "Bridge construction",
  structural_engineer: "Bridge design",
  fashion_designer: "Luxury products",
  luxury_brand_manager: "Global brand management",
  retail_manager: "Omni-channel sales",
  ecommerce_director: "Global logistics",
  food_beverage_director: "Food chains",
  hospitality_manager: "Customer experience",
  sports_coach: "Game strategy",
  sports_agent: "Sponsorship deals",
  education_consultant: "Remote learning",
  university_president: "Academic leadership",
  financial_advisor: "Wealth building",
  real_estate_broker: "Negotiations",
  construction_manager: "Urban design",
  music_producer: "Hit production",
  film_director: "Cinematic experiences",
  actor: "Performance coaching",
  digital_marketing: "Funnel growth",
  seo_specialist: "SEO playbooks",
  ppc_specialist: "ROI growth",
  vr_ar_developer: "VR/AR products",
  game_designer: "IP creation",
  esports_coach: "Tournament prep",
  customer_success: "CS playbooks",
  call_center_manager: "Customer service",
  event_planner: "Luxury events",
  transportation_manager: "EV logistics",
  aviation_manager: "Global travel",
  biotech_scientist: "Gene editing",
  genetic_engineer: "DNA sequencing",
  medical_doctor: "Cardiology",
  neurosurgeon: "Cognitive AI",
  business_analyst: "KPI reporting",
  compliance_officer: "Legal checks",
  cold_calling: "Objection handling",
  lead_qualification: "Lead scoring",
  sales_business_development: "Partnership deals",
};

// Define example actions for each role
export const botExampleActions = {
  ceo: "Launch new AI vertical",
  coo: "Optimize operations workflow",
  cfo: "Predict financial runway",
  cio: "Upgrade tech stack recommendation",
  cto: "Plan for scalable infrastructure",
  cmo: "Launch major campaigns",
  chro: "Launch employee engagement survey",
  vp_sales: "Create cold call scripts",
  vp_product: "Launch MVP feedback cycles",
  vp_operations: "Build global delivery pipelines",
  data_scientist: "Predict customer churn",
  ml_engineer: "Build smarter AI personas",
  chief_data_officer: "Setup data warehouse structure",
  ux_designer: "Redesign mobile app experience",
  brand_strategist: "Brand refresh strategy",
  innovation_manager: "Suggest disruptive ideas",
  supply_chain_manager: "Reduce delivery time recommendations",
  manufacturing_engineer: "Build smart manufacturing plan",
  venture_capitalist: "Raise funding rounds",
  investment_banker: "Launch public offering prep",
  risk_manager: "Risk score for each strategy",
  marketing: "Coordinate product launch event",
  growth_hacker: "Design viral referral program",
  software_engineer: "Enforce clean code guidelines",
  cloud_architect: "Migrate infrastructure to cloud",
  blockchain_developer: "Build decentralized applications",
  ai_ethics_researcher: "Build fairness audits",
  legal_counsel: "Draft AI usage policies",
  cybersecurity_specialist: "Build security incident response plan",
  content_creator: "Plan content calendar",
  public_relations: "Build press kit for new launches",
  journalist: "Write company news articles",
  diplomat: "Build partnerships abroad",
  political_campaign_manager: "Launch advocacy campaigns",
  strategic_partnerships: "Build B2B alliances",
  sustainability_officer: "Launch green corporate initiative",
  renewable_energy_engineer: "Build solar panel deployment plan",
  electric_vehicle_engineer: "Launch battery research",
  aerospace_engineer: "Plan satellite launch operations",
  architect: "Build futuristic HQ plans",
  civil_engineer: "Design smart transport systems",
  structural_engineer: "Design futuristic public spaces",
  fashion_designer: "Launch limited edition line",
  luxury_brand_manager: "Build LVMH-style conglomerate",
  retail_manager: "Launch digital stores",
  ecommerce_director: "Build Amazon-style operations",
  food_beverage_director: "Build hospitality ventures",
  hospitality_manager: "Launch global hotel loyalty programs",
  sports_coach: "Launch elite training camps",
  sports_agent: "Negotiate star player deals",
  education_consultant: "Launch online academy",
  university_president: "Build global online universities",
  financial_advisor: "Launch financial literacy programs",
  real_estate_broker: "Launch property investment fund",
  construction_manager: "Plan large-scale urban developments",
  music_producer: "Build record label ventures",
  film_director: "Launch global media studios",
  actor: "Launch acting masterclasses",
  digital_marketing: "Run 360° digital campaigns",
  seo_specialist: "Optimize websites for growth",
  ppc_specialist: "Launch performance ad campaigns",
  vr_ar_developer: "Build virtual experience products",
  game_designer: "Launch AAA game titles",
  esports_coach: "Launch esports academies",
  customer_success: "Launch CS success programs",
  call_center_manager: "Build high-volume call centers",
  event_planner: "Plan celebrity events",
  transportation_manager: "Launch urban transport programs",
  aviation_manager: "Launch luxury airline services",
  biotech_scientist: "Launch CRISPR projects",
  genetic_engineer: "Set up genetic data platform",
  medical_doctor: "Build healthcare AI integrations",
  neurosurgeon: "Brain-machine interface research",
  business_analyst: "Analyze quarterly growth data",
  compliance_officer: "GDPR and SOC2 checklist",
  cold_calling: "Build high-conversion call scripts",
  lead_qualification: "Develop lead scoring system",
  sales_business_development: "Create strategic partnership roadmaps",
};

// Define industry expertise for executives
export const executiveIndustryExpertise = {
  healthcare: [
    "Regulatory compliance",
    "Patient experience",
    "Clinical trials",
    "Healthcare technology",
  ],
  technology: [
    "Digital transformation",
    "Software development",
    "Cloud architecture",
    "Cybersecurity",
  ],
  finance: [
    "Risk management",
    "Investment strategy",
    "Financial regulations",
    "Market analysis",
  ],
  retail: [
    "Consumer behavior",
    "Omnichannel strategy",
    "Supply chain optimization",
    "Brand development",
  ],
  manufacturing: [
    "Lean production",
    "Quality assurance",
    "Supply chain management",
    "Operational efficiency",
  ],
};
