import { User, Session } from '@supabase/supabase-js';
import { Json } from '@/utils/profileHelpers';
export type Profile = {
    id: string;
    user_id?: string;
    email?: string;
    username?: string;
    full_name?: string;
    avatar_url?: string;
    company_id?: string;
    role?: string;
    last_activity?: string;
    created_at?: string;
    updated_at?: string;
    name?: string;
    company?: string;
    phone?: string;
    location?: string;
    website?: string;
    bio?: string;
    personal_api_keys?: Record<string, string> | string | null | Json;
    industry?: string;
    stripe_customer_id?: string;
    subscription_status?: string;
    subscription_plan_id?: string;
    subscription_expires_at?: string;
    company_size?: string;
    risk_appetite?: string;
    goals?: string[];
};
export declare function useAuthState(): {
    user: User;
    session: Session;
    profile: Profile;
    isLoading: boolean;
    isProfileLoading: boolean;
    isEmailVerified: boolean;
    authError: string;
    loadUserProfile: (userId: string) => Promise<void>;
    refreshSession: () => Promise<boolean>;
    updateLastActivity: () => Promise<void>;
    setProfile: import("react").Dispatch<import("react").SetStateAction<Profile>>;
    hasInitialized: boolean;
};
