import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AccordionContent, AccordionItem, AccordionTrigger, } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Plus, X, ArrowRight } from "lucide-react";
export function AiReadiness({ companyDetails, handleTextChange, newItem, setNewItem, addToArray, removeFromArray, onNext, }) {
    return (_jsxs(AccordionItem, { value: "ai", children: [_jsx(AccordionTrigger, { className: "text-base font-medium", children: "AI/Automation Readiness" }), _jsxs(AccordionContent, { className: "space-y-4 pt-4", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium", children: "Current Use of AI or Automation" }), _jsx(Textarea, { placeholder: "Any automation already in place?", value: companyDetails.currentAiUse || "", onChange: (e) => handleTextChange("currentAiUse", e.target.value) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium", children: "AI Opportunities" }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Input, { placeholder: "Where can AI improve your business?", value: newItem.aiOpportunities || "", onChange: (e) => setNewItem(Object.assign(Object.assign({}, newItem), { aiOpportunities: e.target.value })) }), _jsx(Button, { type: "button", size: "icon", onClick: () => addToArray("aiOpportunities"), children: _jsx(Plus, { className: "h-4 w-4" }) })] }), _jsx("div", { className: "flex flex-wrap gap-2 mt-2", children: (companyDetails.aiOpportunities || []).map((opportunity, index) => (_jsxs("div", { className: "flex items-center bg-secondary text-secondary-foreground px-3 py-1 rounded-full text-sm", children: [opportunity, _jsx("button", { onClick: () => removeFromArray("aiOpportunities", index), className: "ml-2 text-muted-foreground hover:text-foreground", children: _jsx(X, { className: "h-3 w-3" }) })] }, index))) })] }), _jsx("div", { className: "flex justify-end mt-4", children: _jsxs(Button, { onClick: (e) => onNext && onNext("ai"), className: "gap-2", children: ["Continue to Financial Overview", _jsx(ArrowRight, { className: "h-4 w-4" })] }) })] })] }));
}
