import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AccordionContent, AccordionItem, AccordionTrigger, } from "@/components/ui/accordion";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";
export function FinancialOverview({ companyDetails, handleTextChange, onNext, }) {
    return (_jsxs(AccordionItem, { value: "financial", children: [_jsx(AccordionTrigger, { className: "text-base font-medium", children: "Financial Overview" }), _jsxs(AccordionContent, { className: "space-y-4 pt-4", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium", children: "Current Financials" }), _jsx(Textarea, { placeholder: "Profit/Loss, Cash Flow", value: companyDetails.financials || "", onChange: (e) => handleTextChange("financials", e.target.value) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium", children: "Burn Rate" }), _jsx(Input, { placeholder: "Monthly cash spend", value: companyDetails.burnRate || "", onChange: (e) => handleTextChange("burnRate", e.target.value) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium", children: "Runway" }), _jsx(Input, { placeholder: "How many months left before needing new funding?", value: companyDetails.runway || "", onChange: (e) => handleTextChange("runway", e.target.value) })] }), _jsx("div", { className: "flex justify-end mt-4", children: _jsxs(Button, { onClick: (e) => onNext && onNext("financial"), className: "gap-2", children: ["Continue to Strategic Goals", _jsx(ArrowRight, { className: "h-4 w-4" })] }) })] })] }));
}
