import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AccordionContent, AccordionItem, AccordionTrigger, } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Plus, X, ArrowRight } from "lucide-react";
export function StrategicGoals({ companyDetails, handleTextChange, newItem, setNewItem, addToArray, removeFromArray, onNext, }) {
    return (_jsxs(AccordionItem, { value: "goals", children: [_jsx(AccordionTrigger, { className: "text-base font-medium", children: "Strategic Goals" }), _jsxs(AccordionContent, { className: "space-y-4 pt-4", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium", children: "12-Month Plan" }), _jsx(Textarea, { placeholder: "What are your goals for the next year?", value: companyDetails.shortTermPlan || "", onChange: (e) => handleTextChange("shortTermPlan", e.target.value) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium", children: "3-5 Year Vision" }), _jsx(Textarea, { placeholder: "What's your long-term vision?", value: companyDetails.longTermVision || "", onChange: (e) => handleTextChange("longTermVision", e.target.value) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium", children: "Key Challenges" }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Input, { placeholder: "Add a challenge", value: newItem.challenges || "", onChange: (e) => setNewItem(Object.assign(Object.assign({}, newItem), { challenges: e.target.value })) }), _jsx(Button, { type: "button", size: "icon", onClick: () => addToArray("challenges"), children: _jsx(Plus, { className: "h-4 w-4" }) })] }), _jsx("div", { className: "flex flex-wrap gap-2 mt-2", children: (companyDetails.challenges || []).map((challenge, index) => (_jsxs("div", { className: "flex items-center bg-secondary text-secondary-foreground px-3 py-1 rounded-full text-sm", children: [challenge, _jsx("button", { onClick: () => removeFromArray("challenges", index), className: "ml-2 text-muted-foreground hover:text-foreground", children: _jsx(X, { className: "h-3 w-3" }) })] }, index))) })] }), _jsx("div", { className: "flex justify-end mt-4", children: _jsxs(Button, { onClick: (e) => onNext && onNext("goals"), className: "gap-2", children: ["Continue to Special Info", _jsx(ArrowRight, { className: "h-4 w-4" })] }) })] })] }));
}
