import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AccordionContent, AccordionItem, AccordionTrigger, } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Plus, X, ArrowRight } from "lucide-react";
export function TeamLeadership({ companyDetails, handleTextChange, newItem, setNewItem, addToArray, removeFromArray, handleNumberChange, onNext, }) {
    return (_jsxs(AccordionItem, { value: "team", children: [_jsx(AccordionTrigger, { className: "text-base font-medium", children: "Team & Leadership" }), _jsxs(AccordionContent, { className: "space-y-4 pt-4", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium", children: "Founders and Key Team" }), _jsx(Textarea, { placeholder: "Backgrounds, experience, notable wins?", value: companyDetails.founders || "", onChange: (e) => handleTextChange("founders", e.target.value) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium", children: "Team Size" }), _jsx(Input, { type: "number", placeholder: "Number of employees", value: companyDetails.teamSize || "", onChange: (e) => handleNumberChange &&
                                    handleNumberChange("teamSize", e.target.value) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium", children: "Culture & Values" }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Input, { placeholder: "Add a culture value", value: newItem.cultureValues || "", onChange: (e) => setNewItem(Object.assign(Object.assign({}, newItem), { cultureValues: e.target.value })) }), _jsx(Button, { type: "button", size: "icon", onClick: () => addToArray("cultureValues"), children: _jsx(Plus, { className: "h-4 w-4" }) })] }), _jsx("div", { className: "flex flex-wrap gap-2 mt-2", children: (companyDetails.cultureValues || []).map((value, index) => (_jsxs("div", { className: "flex items-center bg-secondary text-secondary-foreground px-3 py-1 rounded-full text-sm", children: [value, _jsx("button", { onClick: () => removeFromArray("cultureValues", index), className: "ml-2 text-muted-foreground hover:text-foreground", children: _jsx(X, { className: "h-3 w-3" }) })] }, index))) })] }), _jsx("div", { className: "flex justify-end mt-4", children: _jsxs(Button, { onClick: (e) => onNext && onNext("team"), className: "gap-2", children: ["Continue to Marketing & Sales", _jsx(ArrowRight, { className: "h-4 w-4" })] }) })] })] }));
}
