import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter, CardHeader, CardTitle, } from "@/components/ui/card";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, } from "@/components/ui/dropdown-menu";
import { LeadStatusBadge } from "@/components/admin/leads/LeadStatusBadge";
import { LeadScoreBadge } from "./LeadScoreBadge";
import { MoreHorizontal, Phone, Mail } from "lucide-react";
export const MobileLeadCards = ({ leads, onViewLead, onStatusUpdate, onDelete, getLeadScore, getNextBestAction, }) => {
    return (_jsx("div", { className: "space-y-4", children: leads.map((lead) => {
            const leadScore = getLeadScore(lead);
            const nextAction = getNextBestAction(lead);
            return (_jsxs(Card, { className: "overflow-hidden", children: [_jsx(CardHeader, { className: "pb-2", children: _jsxs("div", { className: "flex justify-between items-start", children: [_jsx(CardTitle, { className: "text-base font-medium", children: lead.name }), _jsxs("div", { className: "flex gap-2", children: [_jsx(LeadStatusBadge, { status: lead.status }), _jsx(LeadScoreBadge, { score: leadScore })] })] }) }), _jsx(CardContent, { className: "pb-2", children: _jsxs("div", { className: "grid gap-1", children: [lead.email && (_jsxs("div", { className: "flex items-center text-sm", children: [_jsx(Mail, { className: "h-4 w-4 mr-2 text-muted-foreground" }), _jsx("span", { children: lead.email })] })), lead.phone && (_jsxs("div", { className: "flex items-center text-sm", children: [_jsx(Phone, { className: "h-4 w-4 mr-2 text-muted-foreground" }), _jsx("span", { children: lead.phone })] })), _jsxs("div", { className: "pt-2 text-sm", children: [_jsx("span", { className: "font-medium", children: "Next action: " }), nextAction] }), _jsxs("div", { className: "text-xs text-muted-foreground pt-1", children: ["Added on ", new Date(lead.created_at).toLocaleDateString()] })] }) }), _jsxs(CardFooter, { className: "flex justify-between pt-2", children: [_jsx(Button, { size: "sm", variant: "secondary", onClick: () => onViewLead(lead), children: "View Details" }), _jsxs(DropdownMenu, { children: [_jsx(DropdownMenuTrigger, { asChild: true, children: _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8", children: _jsx(MoreHorizontal, { className: "h-4 w-4" }) }) }), _jsxs(DropdownMenuContent, { align: "end", children: [_jsx(DropdownMenuItem, { onClick: () => onStatusUpdate(lead.id, "contacted"), children: "Mark as Contacted" }), _jsx(DropdownMenuItem, { onClick: () => onStatusUpdate(lead.id, "qualified"), children: "Mark as Qualified" }), _jsx(DropdownMenuItem, { onClick: () => onDelete(lead.id), className: "text-destructive", children: "Delete" })] })] })] })] }, lead.id));
        }) }));
};
