
import Navbar from "@/components/Navbar";
import { ScrollArea } from "@/components/ui/scroll-area";

export default function Legal() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <div className="flex-1 container mx-auto px-4 py-24">
        <h1 className="text-3xl font-bold mb-8">Legal Notice</h1>
        
        <ScrollArea className="bg-secondary/40 border border-border/50 rounded-lg p-6 h-[60vh]">
          <div className="space-y-6">
            <section>
              <h2 className="text-xl font-bold mb-4">1. Terms of Service</h2>
              <p className="text-gray-300">
                All content generated by Allora AI is AI-assisted and follows compliance standards. 
                By using our services, you agree to these terms and conditions. The AI-generated 
                content provided by Allora AI is for informational purposes only and does not 
                constitute legal, financial, or business advice.
              </p>
            </section>
            
            <section>
              <h2 className="text-xl font-bold mb-4">2. Intellectual Property</h2>
              <p className="text-gray-300">
                Content generated through Allora AI services is owned by the user, subject to our 
                licensing terms. Allora AI retains ownership of all AI models, algorithms, and 
                proprietary technology used to generate content.
              </p>
            </section>
            
            <section>
              <h2 className="text-xl font-bold mb-4">3. Limitation of Liability</h2>
              <p className="text-gray-300">
                Allora AI provides its services on an "as is" and "as available" basis. We make no 
                warranties, expressed or implied, and hereby disclaim all warranties including, without 
                limitation, implied warranties of merchantability, fitness for a particular purpose, or 
                non-infringement.
              </p>
            </section>
            
            <section>
              <h2 className="text-xl font-bold mb-4">4. Compliance</h2>
              <p className="text-gray-300">
                Users are responsible for ensuring that their use of Allora AI services complies with 
                applicable laws and regulations. Allora AI does not guarantee that its services will 
                meet specific regulatory requirements in all jurisdictions.
              </p>
            </section>
            
            <section>
              <h2 className="text-xl font-bold mb-4">5. Changes to Terms</h2>
              <p className="text-gray-300">
                Allora AI reserves the right to modify these terms at any time. We will provide 
                notification of significant changes through our website or email communications.
              </p>
            </section>
          </div>
        </ScrollArea>
      </div>
    </div>
  );
}
