
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function TermsOfService() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <h1 className="text-4xl font-bold text-center mb-8">Terms of Service</h1>
      
      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>1. Acceptance of Terms</CardTitle>
          </CardHeader>
          <CardContent>
            <p>By accessing or using Allora AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use our platform.</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle>2. Use of Service</CardTitle>
          </CardHeader>
          <CardContent>
            <p>Allora AI provides an AI-powered business strategy platform. You agree to use the service only for lawful purposes and in compliance with all applicable laws and regulations.</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle>3. User Account</CardTitle>
          </CardHeader>
          <CardContent>
            <p>You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account.</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle>4. Intellectual Property</CardTitle>
          </CardHeader>
          <CardContent>
            <p>All content generated by Allora AI's AI executives and the platform's original content are protected by intellectual property laws. Users may not reproduce, distribute, or create derivative works without express permission.</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle>5. Limitation of Liability</CardTitle>
          </CardHeader>
          <CardContent>
            <p>Allora AI provides strategies and recommendations as guidance. We are not responsible for direct, indirect, incidental, or consequential damages resulting from the use of our platform.</p>
          </CardContent>
        </Card>
      </div>
      
      <div className="mt-8 text-center text-sm text-muted-foreground">
        <p>Last Updated: {new Date().toLocaleDateString()}</p>
        <p>© {new Date().getFullYear()} Allora AI. All Rights Reserved.</p>
      </div>
    </div>
  );
}
