import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { getStatusIcon, getStatusColorClass } from "../utils/statusUtils";
export default function ServicesTab({ services }) {
    return (_jsxs(Card, { children: [_jsxs(CardHeader, { className: "pb-2", children: [_jsx(CardTitle, { children: "Service Status" }), _jsx(CardDescription, { children: "Detailed status of all system services" })] }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-4", children: [services.map((service) => (_jsxs(Card, { className: "mb-4 overflow-hidden", children: [_jsx("div", { className: `w-full h-1 ${service.status === "healthy"
                                        ? "bg-green-500"
                                        : service.status === "degraded"
                                            ? "bg-amber-500"
                                            : "bg-red-500"}` }), _jsxs(CardContent, { className: "p-4", children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-lg", children: service.name }), _jsx("p", { className: "text-sm text-muted-foreground", children: service.description })] }), _jsx(Badge, { variant: "outline", className: getStatusColorClass(service.status), children: _jsxs("div", { className: "flex items-center gap-1", children: [_jsx("div", { className: "flex-shrink-0", children: getStatusIcon(service.status) }), _jsx("span", { className: "capitalize", children: service.status })] }) })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4 mt-4", children: [_jsxs("div", { children: [_jsx("div", { className: "text-sm text-muted-foreground", children: "Response Time" }), _jsxs("div", { className: "font-medium", children: [service.responseTime, " ms"] })] }), _jsxs("div", { children: [_jsx("div", { className: "text-sm text-muted-foreground", children: "Last Checked" }), _jsx("div", { className: "font-medium", children: new Date(service.lastChecked).toLocaleString() })] })] }), service.details && (_jsxs("div", { className: "mt-4 pt-4 border-t", children: [_jsx("div", { className: "text-sm text-muted-foreground", children: "Details" }), _jsx("div", { className: "font-medium", children: service.details })] }))] })] }, service.id))), services.length === 0 && (_jsx("div", { className: "text-center py-12 text-muted-foreground", children: _jsx("p", { children: "No services to display" }) }))] }) })] }));
}
