import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useExecutiveDebate } from "@/hooks/useExecutiveDebate";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, } from "@/components/ui/card";
import { formatRoleTitle } from "@/utils/consultation";
import { Lightbulb, Users, CheckCircle, MessageSquare, Briefcase, Brain, } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
const ExecutiveBoardroom = () => {
    const { debateMessages, debateSummary, isLoading } = useExecutiveDebate();
    if (isLoading) {
        return (_jsx("div", { className: "space-y-6", children: _jsxs(Card, { children: [_jsxs(CardHeader, { className: "pb-3", children: [_jsx(Skeleton, { className: "h-6 w-3/4" }), _jsx(Skeleton, { className: "h-4 w-1/2 mt-2" })] }), _jsx(CardContent, { children: _jsx("div", { className: "space-y-4", children: [1, 2, 3].map((i) => (_jsxs("div", { className: "flex gap-4", children: [_jsx(Skeleton, { className: "h-12 w-12 rounded-full" }), _jsxs("div", { className: "space-y-2 flex-1", children: [_jsx(Skeleton, { className: "h-4 w-1/3" }), _jsx(Skeleton, { className: "h-16 w-full" })] })] }, i))) }) })] }) }));
    }
    return (_jsx("div", { className: "space-y-6", children: _jsxs(Tabs, { defaultValue: "debate", className: "space-y-4", children: [_jsxs(TabsList, { className: "mb-2", children: [_jsxs(TabsTrigger, { value: "debate", className: "flex items-center gap-2", children: [_jsx(MessageSquare, { className: "h-4 w-4" }), _jsx("span", { children: "Debate Transcript" })] }), _jsxs(TabsTrigger, { value: "summary", className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "h-4 w-4" }), _jsx("span", { children: "Decision Summary" })] }), _jsxs(TabsTrigger, { value: "contributors", className: "flex items-center gap-2", children: [_jsx(Users, { className: "h-4 w-4" }), _jsx("span", { children: "Key Contributors" })] }), _jsxs(TabsTrigger, { value: "process", className: "flex items-center gap-2", children: [_jsx(Brain, { className: "h-4 w-4" }), _jsx("span", { children: "Thinking Process" })] })] }), _jsx(TabsContent, { value: "debate", children: _jsxs(Card, { children: [_jsxs(CardHeader, { className: "pb-3", children: [_jsx(CardTitle, { className: "text-xl font-bold", children: "Executive Boardroom Debate" }), _jsx(CardDescription, { children: "See how our AI executive team analyzed your company's needs and debated the best strategic approach" })] }), _jsx(CardContent, { children: _jsx("div", { className: "space-y-6", children: debateMessages.map((message) => (_jsxs("div", { className: "flex gap-4", children: [_jsxs(Avatar, { className: "h-12 w-12 border-2 border-background", children: [_jsx(AvatarImage, { src: message.executive.avatar, alt: message.executive.name }), _jsx(AvatarFallback, { children: message.executive.name.charAt(0) })] }), _jsxs("div", { className: "space-y-1 flex-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "font-medium", children: message.executive.name }), _jsx("span", { className: "text-xs text-muted-foreground", children: message.executive.role ||
                                                                    formatRoleTitle(message.executive.role || "") })] }), _jsx("div", { className: "bg-secondary/10 rounded-lg p-3", children: _jsx("p", { children: message.content }) })] })] }, message.id))) }) })] }) }), _jsx(TabsContent, { value: "summary", children: _jsxs(Card, { children: [_jsxs(CardHeader, { className: "pb-3", children: [_jsx(CardTitle, { className: "text-xl font-bold", children: "Decision Summary" }), _jsx(CardDescription, { children: "The key decisions and recommendations from the executive team" })] }), _jsx(CardContent, { children: _jsx("div", { className: "bg-secondary/10 rounded-lg p-4", children: _jsx("p", { children: typeof debateSummary === "string"
                                            ? debateSummary
                                            : "No summary is available for this debate yet." }) }) })] }) }), _jsx(TabsContent, { value: "contributors", children: _jsxs(Card, { children: [_jsxs(CardHeader, { className: "pb-3", children: [_jsx(CardTitle, { className: "text-xl font-bold", children: "Key Contributors" }), _jsx(CardDescription, { children: "The executive team members who contributed to this analysis" })] }), _jsx(CardContent, { children: _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: debateMessages
                                        .filter((m, i, arr) => arr.findIndex((m2) => m2.executive.name === m.executive.name) === i)
                                        .map((message) => (_jsxs("div", { className: "flex items-center gap-3 p-3 bg-secondary/10 rounded-lg", children: [_jsxs(Avatar, { className: "h-10 w-10 border-2 border-primary/20", children: [_jsx(AvatarImage, { src: message.executive.avatar, alt: message.executive.name }), _jsx(AvatarFallback, { children: message.executive.name.charAt(0) })] }), _jsxs("div", { children: [_jsx("p", { className: "font-medium", children: message.executive.name }), _jsx("p", { className: "text-xs text-muted-foreground", children: message.executive.role ||
                                                            formatRoleTitle(message.executive.role || "") })] })] }, message.executive.name))) }) })] }) }), _jsx(TabsContent, { value: "process", children: _jsxs(Card, { children: [_jsxs(CardHeader, { className: "pb-3", children: [_jsx(CardTitle, { className: "text-xl font-bold", children: "Thinking Process" }), _jsx(CardDescription, { children: "How our AI executive team approached the analysis of your business needs" })] }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-secondary/10 rounded-lg p-4", children: [_jsxs("h3", { className: "font-medium mb-2 flex items-center gap-2", children: [_jsx(Lightbulb, { className: "h-4 w-4 text-amber-400" }), "Analysis Methodology"] }), _jsx("p", { className: "text-sm", children: "Our AI executive team analyzes your business information through multiple perspectives, using industry-specific knowledge and strategic frameworks to provide comprehensive insights." })] }), _jsxs("div", { className: "bg-secondary/10 rounded-lg p-4", children: [_jsxs("h3", { className: "font-medium mb-2 flex items-center gap-2", children: [_jsx(Briefcase, { className: "h-4 w-4 text-blue-400" }), "Business Context Integration"] }), _jsx("p", { className: "text-sm", children: "The team integrates your specific business context with market trends, competitive analysis, and growth opportunities to create tailored recommendations." })] })] }) })] }) })] }) }));
};
export default ExecutiveBoardroom;
