import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { FileDown } from "lucide-react";
export default function StrategyFilters({ searchQuery, setSearchQuery, riskFilter, setRiskFilter, sortBy, setSortBy, onExportAll, isMobile, }) {
    return (_jsx("div", { className: "bg-gray-900/50 backdrop-blur-sm border border-gray-800 rounded-lg p-4 mb-6", children: _jsxs("div", { className: "flex flex-col md:flex-row gap-3", children: [_jsxs("div", { className: "relative flex-1", children: [_jsx("input", { type: "text", placeholder: "Search strategies...", value: searchQuery, onChange: (e) => setSearchQuery(e.target.value), className: "w-full py-2 px-4 pl-10 bg-gray-800/70 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-purple-500" }), _jsx("svg", { className: "absolute left-3 top-3 h-4 w-4 text-gray-500", xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" }) })] }), _jsxs("div", { className: "flex gap-3", children: [_jsxs("select", { value: riskFilter, onChange: (e) => setRiskFilter(e.target.value), className: "py-2 px-4 bg-gray-800/70 border border-gray-700 rounded-lg text-white appearance-none focus:outline-none focus:ring-1 focus:ring-purple-500", children: [_jsx("option", { value: "all", children: "All Risks" }), _jsx("option", { value: "Low", children: "Low Risk" }), _jsx("option", { value: "Medium", children: "Medium Risk" }), _jsx("option", { value: "High", children: "High Risk" })] }), _jsxs("button", { className: "py-2 px-4 bg-gray-800/70 border border-gray-700 rounded-lg text-white flex items-center gap-2 hover:bg-gray-700/70 transition-colors", onClick: () => {
                                const nextSort = sortBy === "newest" ? "oldest" : "newest";
                                setSortBy(nextSort);
                            }, children: [_jsx("svg", { className: "h-5 w-5", xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M3 4h13M3 8h9m-9 4h6m4 0l4-4m0 0l4 4m-4-4v12" }) }), "Sort"] }), !isMobile && (_jsxs(Button, { variant: "outline", className: "hidden md:flex border-gray-700 bg-gray-800/50 hover:bg-gray-700/50", onClick: onExportAll, children: [_jsx(FileDown, { className: "mr-2 h-4 w-4" }), "Export All"] }))] })] }) }));
}
