import React from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ExternalLink } from "lucide-react";
const TrendReportModal = ({ isOpen, onClose, trendData }) => {
    if (!trendData)
        return null;
    return (<Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold">{trendData.title}</DialogTitle>
          <DialogDescription className="text-muted-foreground">
            AI industry trend analysis and strategic recommendations
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6">
          {/* Main content */}
          <div className="text-foreground">
            <p className="mb-4">{trendData.content}</p>
            
            {/* Key Insights */}
            <h3 className="text-lg font-medium mb-2">Key Insights</h3>
            <ul className="space-y-2 mb-6">
              {trendData.insights.map((insight, index) => (<li key={index} className="flex items-start">
                  <span className="text-primary mr-2">•</span>
                  <span>{insight}</span>
                </li>))}
            </ul>
            
            {/* Strategic Recommendations */}
            <h3 className="text-lg font-medium mb-2">Strategic Recommendations</h3>
            <ul className="space-y-2 mb-6">
              {trendData.recommendations.map((recommendation, index) => (<li key={index} className="flex items-start">
                  <span className="text-primary mr-2">•</span>
                  <span>{recommendation}</span>
                </li>))}
            </ul>
            
            {/* Related Strategies */}
            <div className="bg-muted/40 p-4 rounded-lg mb-6">
              <h3 className="text-lg font-medium mb-2">Affected Strategies</h3>
              <div className="flex flex-wrap gap-2">
                {trendData.relatedStrategies.map((strategy, index) => (<span key={index} className="bg-primary/10 text-primary px-3 py-1 rounded-full text-sm">
                    {strategy}
                  </span>))}
              </div>
            </div>
          </div>
          
          {/* Footer with external link */}
          <div className="flex justify-between items-center pt-4 border-t">
            <div className="text-sm text-muted-foreground">
              Report generated by AI Executive Team
            </div>
            {trendData.externalLink && (<Button variant="outline" size="sm" asChild>
                <a href={trendData.externalLink} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2">
                  More Information
                  <ExternalLink className="h-4 w-4"/>
                </a>
              </Button>)}
          </div>
        </div>
      </DialogContent>
    </Dialog>);
};
export default TrendReportModal;
