"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.botSpecialSkills = void 0;
var botSpecialSkills = {
  ceo: "visionary",
  cto: "technical leadership",
  cfo: "finance",
  coo: "operations",
  cmo: "marketing",
  hr: "people",
  sales: "revenue",
  support: "customer service",
  product: "product management",
  design: "creativity",
  engineering: "development",
  qa: "quality assurance",
  data: "analytics",
  legal: "compliance",
  pr: "public relations",
  it: "infrastructure",
  admin: "administration",
  research: "innovation",
  strategy: "planning",
  partnerships: "collaboration",
  community: "engagement",
  content: "creation",
  growth: "expansion",
  ux: "user experience",
  ui: "interface design",
  devops: "deployment",
  security: "protection",
  training: "education",
  procurement: "sourcing",
  logistics: "distribution",
  facilities: "maintenance",
  events: "coordination",
  investor: "relations",
  media: "communication",
  government: "affairs",
  philanthropy: "charity",
  sustainability: "environment",
  innovation: "creativity",
  culture: "values",
  diversity: "inclusion",
  wellbeing: "health",
  remote: "telecommuting",
  freelance: "contracting",
  intern: "learning",
  volunteer: "service",
  alumni: "networking",
  mentor: "guidance",
  advisor: "consulting",
  ambassador: "representation",
  influencer: "promotion",
  analyst: "research",
  architect: "design",
  artist: "creativity",
  author: "writing",
  blogger: "content",
  broadcaster: "media",
  coach: "training",
  consultant: "advice",
  critic: "review",
  curator: "selection",
  designer: "creativity",
  developer: "coding",
  director: "management",
  editor: "content",
  educator: "teaching",
  engineer: "development",
  entrepreneur: "business",
  executive: "leadership",
  filmmaker: "production",
  founder: "startup",
  journalist: "reporting",
  lawyer: "legal",
  marketer: "promotion",
  musician: "performance",
  photographer: "visuals",
  producer: "production",
  programmer: "coding",
  publicist: "public relations",
  researcher: "analysis",
  scientist: "discovery",
  speaker: "communication",
  strategist: "planning",
  technician: "technical",
  technologist: "innovation",
  writer: "content",
};
exports.botSpecialSkills = botSpecialSkills;
