"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.analyzeStrategy = analyzeStrategy;
// ...existing code...
function analyzeStrategy(level) {
  // ...existing code...
}
// ...existing code...
