import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, } from "@/components/ui/card";
import { MessageSquare, PlusCircle, Info } from "lucide-react";
import { Button } from "@/components/ui/button";
import { HelpTooltip } from "@/components/help/HelpTooltip";
import { DocumentationLink } from "@/components/help/HelpTooltip";
export const EmptyDebateState = ({ onStartNewDebate }) => {
    return (_jsxs(Card, { className: "shadow-md", children: [_jsxs(CardHeader, { className: "pb-2", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx(CardTitle, { className: "text-lg", children: "AI Executive Boardroom" }), _jsx(HelpTooltip, { content: _jsxs("div", { className: "space-y-2", children: [_jsx("p", { children: "The AI Executive Boardroom simulates strategic discussions between AI personas modeled after executives with different perspectives." }), _jsx(DocumentationLink, { href: "/help/ai-boardroom", label: "Learn more about AI boardroom debates" })] }), children: _jsx(Info, { className: "h-4 w-4 text-muted-foreground cursor-help" }) })] }), _jsx(CardDescription, { children: "No active debates found" })] }), _jsx(CardContent, { className: "py-4", children: _jsxs("div", { className: "flex flex-col items-center text-center", children: [_jsx(MessageSquare, { className: "h-12 w-12 text-muted-foreground mb-3" }), _jsx("p", { className: "text-sm text-muted-foreground mb-4", children: "There are no active executive debates for your company. AI executive debates help generate strategic insights by simulating discussions between different executive perspectives." }), _jsxs("div", { className: "space-y-2", children: [_jsxs(Button, { variant: "default", onClick: onStartNewDebate, className: "gap-2", children: [_jsx(PlusCircle, { className: "h-4 w-4" }), "Start New Debate"] }), _jsx("p", { className: "text-xs text-muted-foreground mt-2", children: "You'll be able to select a topic and choose which AI executive personas should participate in the debate." })] })] }) })] }));
};
