import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Avatar } from "@/components/ui/avatar";
import { UserCircle, ThumbsUp, ThumbsDown, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
const DebateMessage = ({ message, participants, onVote, onToggleFavorite }) => {
    const participant = participants.find((p) => p.id === message.senderId);
    return (_jsxs("div", { className: `flex gap-4 p-3 rounded-lg ${message.isUser ? "bg-muted/50" : "bg-card"} ${message.isFavorite ? "border-2 border-yellow-400" : "border border-border"}`, children: [_jsx("div", { className: "flex-shrink-0", children: message.isUser ? (_jsx("div", { className: "w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center", children: _jsx(UserCircle, { className: "h-6 w-6 text-primary" }) })) : message.senderId === "system" ? (_jsx("div", { className: "w-10 h-10 rounded-full bg-muted flex items-center justify-center", children: _jsx("span", { className: "text-muted-foreground font-semibold", children: "S" }) })) : (_jsx(Avatar, { className: "h-10 w-10", children: _jsx("div", { className: "w-full h-full flex items-center justify-center bg-primary/10", children: _jsx("span", { className: "font-semibold", children: message.sender.charAt(0) }) }) })) }), _jsxs("div", { className: "flex-1 space-y-1", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { children: [_jsx("span", { className: "font-medium", children: message.sender }), participant && (_jsx("span", { className: "text-sm text-muted-foreground ml-2", children: participant.title }))] }), _jsx("div", { className: "text-xs text-muted-foreground", children: message.timestamp.toLocaleTimeString([], {
                                    hour: "2-digit",
                                    minute: "2-digit",
                                }) })] }), _jsx("div", { className: "text-sm", children: message.content }), !message.senderId.includes("system") && (_jsxs("div", { className: "flex items-center gap-2 pt-2", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8", onClick: () => onVote && onVote(message.id, true), disabled: !onVote, children: _jsx(ThumbsUp, { className: "h-4 w-4" }) }), _jsx("span", { className: "text-sm mx-1", children: message.votes || 0 }), _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8", onClick: () => onVote && onVote(message.id, false), disabled: !onVote || (message.votes || 0) <= 0, children: _jsx(ThumbsDown, { className: "h-4 w-4" }) })] }), _jsx(Button, { variant: "ghost", size: "icon", className: cn("h-8 w-8", message.isFavorite && "text-yellow-500"), onClick: () => onToggleFavorite && onToggleFavorite(message.id), disabled: !onToggleFavorite, children: _jsx(Star, { className: "h-4 w-4", fill: message.isFavorite ? "currentColor" : "none" }) })] }))] })] }));
};
export default DebateMessage;
